apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calculator-deployment
spec:
  selector:
    matchLabels:
      app: calculator-app
  serviceName: "calculator-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: calculator-app
          image: sit737-2025-prac7p
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: mongodb-config
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-secret
