apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    tier: backend
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator-app
    tier: frontend
spec:
  ports:
    - name: mongo
      port: 3000
      targetPort: 3000
  clusterIP: None
  selector:
    app: calculator-app