version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: sit737-2025-prac7p
    restart: always
    ports:
      - 3000:3000

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

# References
    # https://docs.docker.com/reference/dockerfile/#healthcheck
    # https://last9.io/blog/docker-compose-health-checks/
    
    #command: bash -c /usr/src/app/start.sh
    #env_file: .env