# reference: https:kubectl get nodes//spacelift.io/blog/kubernetes-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculatorapp
    tier: frontend
  name: calculator-nodeport
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: calculatorapp
  selector:
    app: calculatorapp
    tier: frontend
  type: NodePort